networks:
  frontend-network:
    driver: bridge
  backend-network:
    driver: bridge


services:
  express-server-service:
    build:
      context: .
      dockerfile: ./Dockerfile
      target: dev
    container_name: express-dev-container
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - ./app:/app
      - express-node-modules:/app/node_modules
      - express-yarn:/app/.yarn
    environment:
      NODE_ENV: development
      CHOKIDAR_USEPOLLING: true
      MARIADB_USER:          tareas-user
      MARIADB_USER_HOST:     '%'
      MARIADB_PASSWORD:      user-secret
      MARIADB_DATABASE:      tareas-db
    networks:
      - backend-network
      - frontend-network


  mariadb-service:
    image: mariadb:12.3.2-noble
    container_name: mariadb-container
    restart: unless-stopped
    environment:
      PORT:                  '3306'
      MARIADB_USER:          tareas-user
      MARIADB_USER_HOST:     '%'
      MARIADB_PASSWORD:      user-secret
      MARIADB_ROOT_HOST:     '%'
      MARIADB_ROOT_PASSWORD: secret
      MARIADB_DATABASE:      tareas-db
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - backend-network


volumes:
  express-node-modules:
    name: express-dev-node-modules
  express-yarn:
    name: express-dev-yarn-cache
  db-data:
    name: mariadb-data

